--- Luvit Documentation Generation
project='Luvit'
title='Luvit documentation'
description='Lua + libUV + jIT = pure awesomesauce'
format='markdown'
file='lib'
dir='docs'
topics= {
	'README.markdown'; 
	'docs.markdown';
	'api.markdown';
	'errors.markdown';
	}
examples = {
   'examples/http-server.lua';
   'examples/http-client.lua';
   'examples/buffer-basics.lua';
   'examples/child-spawn.lua';
   'examples/child-execfile.lua';
}

